"""
AgroSphere AI - Groq LLM Client
Connects to Groq's high-speed LPU inference engine (Llama-3.3-70b / Llama-3.1-8b)
with automatic intelligent fallback for offline / mock testing.
"""

import os
from typing import Optional, Dict, Any
from groq import Groq
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent.parent))
from src.config import GROQ_API_KEY, GROQ_MODEL

class GroqLLMClient:
    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None):
        self.api_key = api_key or GROQ_API_KEY or os.getenv("GROQ_API_KEY", "")
        self.model = model or GROQ_MODEL or "llama-3.1-8b-instant"
        self.client: Optional[Groq] = None
        
        if self.api_key and len(self.api_key.strip()) > 5:
            try:
                self.client = Groq(api_key=self.api_key.strip())
            except Exception as e:
                print(f"[WARN] Failed to initialize Groq client: {e}. Running in fallback mode.")
                self.client = None

    def is_available(self) -> bool:
        """Returns True if live Groq API connection is active."""
        return self.client is not None

    def generate_completion(self, system_prompt: str, user_prompt: str, temperature: float = 0.3) -> str:
        """
        Calls Groq Chat Completion API with fallback to template engine if key is absent or model error occurs.
        """
        candidate_models = [self.model, "llama-3.1-8b-instant", "llama3-8b-8192", "gemma2-9b-it", "mixtral-8x7b-32768"]
        # Remove duplicates while preserving order
        candidate_models = list(dict.fromkeys(candidate_models))
        
        if self.client:
            for model_name in candidate_models:
                try:
                    response = self.client.chat.completions.create(
                        model=model_name,
                        messages=[
                            {"role": "system", "content": system_prompt},
                            {"role": "user", "content": user_prompt},
                        ],
                        temperature=temperature,
                        max_tokens=800,
                    )
                    return response.choices[0].message.content.strip()
                except Exception as e:
                    print(f"[WARN] Groq model `{model_name}` failed: {e}. Attempting next available model...")

        # Fallback offline generator
        return self._generate_fallback(user_prompt)

    def _generate_fallback(self, user_prompt: str) -> str:
        """High-fidelity fallback text generator when Groq API key is not configured."""
        return (
            "[Auto-Generated by AgroSphere AI Engine]\n\n"
            "Subject: 🚨 Priority Restocking Advisory from Unicrop Biochem\n\n"
            "Based on upcoming meteorological agro-climatic signals and regional demand surge modeling, "
            "we recommend placing an expedited restock order from our Manjusar GIDC facility to avoid stockouts."
        )
